import { v4 as uuid } from "uuid";

export const dataExperience = [
  {
    id: uuid(),
    position: "Founding Software Engineer",
    company: "@Laniva AI",
    time: "Jan 2026 – Present",
    address: "St. John's, NL",
    work: "Architected a SaaS platform using Next.js, PostgreSQL, and AWS, automating property management operations across a portfolio of 350+ residential units. Engineered backend services and REST APIs integrating OpenAI, telephony, SMS, and email to automate tenant communication and maintenance coordination, cutting manual effort by 60-70%. Implemented a Retrieval-Augmented Generation (RAG) pipeline using PostgreSQL with pgvector and structured Q&A segmentation, improving retrieval accuracy by 20%. Deployed scalable AWS Elastic Beanstalk infrastructure with Application Load Balancing and GitHub Actions CI/CD pipelines, cutting manual deployment time from 15-20 minutes to a few minutes.",
  },
  {
    id: uuid(),
    position: "Software Engineer",
    company: "@Memorial University of Newfoundland, Department of History",
    time: "May 2025 – Apr 2026",
    address: "St. John's, NL",
    work: "Designed and implemented Python ETL pipelines to migrate 200K+ records from MySQL to Neo4j, enabling efficient relationship queries while maintaining 100% data integrity. Engineered a Node.js and Express.js backend integrated with Neo4j, exposing 30+ REST APIs for scalable graph querying. Optimized Neo4j graph queries for complex relationships, reducing latency by 60% over legacy relational database queries. Collaborated with a development team throughout the Agile Scrum lifecycle, contributing to sprint planning and delivery.",
  },
  {
    id: uuid(),
    position: "Full Stack Developer",
    company: "@Memorial University of Newfoundland, Department of Psychology",
    time: "May 2025 – Dec 2025",
    address: "St. John's, NL",
    work: "Led development and deployment of a React-based web application serving 500+ students and faculty, improving accessibility and usability of departmental resources. Implemented a Node.js backend with MongoDB, designing RESTful APIs for scalable and reliable data access. Architected an admin management portal enabling faculty to manage site content and monitor activity independently, reducing ongoing developer maintenance. Integrated Azure Blob Storage for media asset management and deployed the application to Azure.",
  },
  {
    id: uuid(),
    position: "Web Developer",
    company: "@MSA at Memorial University",
    time: "Mar 2024 - Jun 2024",
    address: "St. John's, NL",
    work: "Developed and maintained a web application for the student association using Next.js and TypeScript. Incorporated PostgreSQL for efficient database management, showcasing robust data manipulation skills. Built 15+ REST APIs in Next.js, resulting in optimized server-side functionality and seamless data handling.",
  },
  {
    id: uuid(),
    position: "Sponsorship Coordinator ",
    company: "@Hack Frost NL",
    time: "Sep 2023-Present",
    address: "Canada",
    work: " As Sponsorship Coordinator for Hack Frost NL, I create and present compelling sponsorship packages to attract corporate investors, enhancing the value and experience of our hackathon through successful outreach efforts.",
  },
  {
    id: uuid(),
    position: "Online Order Associate",
    company: "@Canadian Tire",
    time: "Jun 2022-Dec 2023",
    address: "Canada",
    work: "I accurately pick and pack online orders, ensuring timely deliveries and meeting customer expectations. In addition to handling online orders, I efficiently stock shelves and maintain organized product displays to enhance the overall shopping experience. By monitoring inventory levels and replenishing stock, I help ensure product availability while also assisting customers with locating items when needed.",
  },
  {
    id: uuid(),
    position: "Self Check Out attendant ",
    company: "@Walmart",
    time: "Oct 2021-Jul 2022",
    address: "Canada",
    work: "I supported customers with self-checkout machines, ensuring smooth transactions and resolving issues quickly. I also trained customers on using the systems, managed payments, and maintained a clean, organized checkout area while monitoring for policy compliance.",
  },
];
